apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: k8s
  name: prometheus-frontend
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 9090
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    app: prometheus
    prometheus: k8s
